spring:
  datasource:
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://INSERT GIVEN URL
    username: INSERT GIVEN USERNAME
    password: "INSERT GIVEN PASSWORD"
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    general-ddl: true
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create
